# Generated by Django 2.2 on 2019-04-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0002_ryot'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='distance',
            field=models.CharField(default='', max_length=70),
        ),
    ]
