export class Plot {
    id:number;
    season:string;
    csi:string;
    section:string;
    offerno:string;
    offerdate:Date;
    planteddate:Date;
    plottype:string;
    plotno:string;
    ryot:string;
    village:string;
    distance:string;
    rationtype:string;
    agreementacre:string;
    agreementedtonne:string;
    measuredarea:string;
    guarantor1:string;
    guarantor2:string;
    guarantorname:string;
}
